seed: 42
output_dir: data/training_samples
num_maps: 2
samples_per_map: 2
map_resolution: 200
shell_thickness: 2
bsp:
  min_leaf_size: 30
  split_range: [0.4, 0.6]
  wall_thickness: 2
doors:
  width_range: [3, 5]
obstacles:
  count_range_per_room: [1, 3]
  door_clearance: 2
  shape_definitions:
    - size_range: [2, 6]
      weight: 1.0
robots:
  - clearance: 0.2
    step_size: 1.0
  - clearance: 0.3
    step_size: 1.5
