seed: 42
output_dir: data/training_samples
num_maps: 2
samples_per_map: 2
map_resolution: 200
shell_thickness: 2
bsp:
  min_leaf_size: 30
  split_range: [0.3, 0.7]
  wall_thickness: 2
doors:
  width_range: [8, 12]
  additional_door_probability: 0.1
obstacles:
  count_range_per_room: [1, 3]
  door_clearance: 2
  obstacle_clearance: 2  
  shape_definitions:
    - type: rectangle
      size_range: [2, 6]
      weight: 0.2
    - type: triangle
      size_range: [2, 6]
      weight: 0.2
    - type: u-shape
      size_range: [2, 6]
      weight: 0.15
    - type: l-shape
      size_range: [2, 6]
      weight: 0.15
    - type: t-shape
      size_range: [2, 6]
      weight: 0.1
robots:
  - clearance: 0.2
    step_size: 1.0
  - clearance: 0.3
    step_size: 1.5
