# Configuration for ground truth visualization
# Path to directory containing generated ground truth .npz files
ground_truth_dir: data/ground_truth
# Directory where cached PRMs are stored
cache_dir: .cache
# PRM parameters used during ground truth generation
samples: 500
k_neighbors: 10
# Toggle optional overlays
show_indices: false
show_prm: true
