# HR-FiLM-Net v2 training configuration
run_name: hr_film_net_v2
seed: 42
model_name: hr_film_net

samples_dir: training_data
ground_truth_dir: ground_truth
val_split: 0.1

checkpoints_dir: checkpoints/hr_film_net_v2
log_dir: logs/hr_film_net_v2

device: cuda
epochs: 20
batch_size: 64
num_workers: 12
use_amp: true
early_stop_patience: 4

optimizer:
  name: AdamW
  lr: 0.0003
  weight_decay: 0.005
  fused: true

scheduler:
  name: CosineAnnealing
  warmup_epochs: 1

loss:
  dice_weight: 0.7
  focal_weight: 0.3
  focal_gamma: 2.0
