# Baseline training configuration for ResNet-FPN-FiLM model
run_name: resnet_fpn_film_v1_baseline
seed: 42
model_name: resnet_fpn_film

samples_dir: training_data
ground_truth_dir: ground_truth
val_split: 0.1

checkpoints_dir: checkpoints/resnet_fpn_film_v1_baseline
log_dir: logs/resnet_fpn_film_v1_baseline

device: cuda
epochs: 25
batch_size: 32
num_workers: 12
use_amp: true
early_stop_patience: 10

optimizer:
  name: AdamW
  lr: 0.0001
  weight_decay: 0.02
  fused: true

scheduler:
  name: CosineAnnealing
  warmup_epochs: 1

loss:
  dice_weight: 0.6
  focal_weight: 0.4
  focal_gamma: 2.0
